openapi: 3.0.0
info:
  title: Stock APIs
  version: "1.0"
servers:
  - url: https://api.iextrading.com/1.0
paths:
  /stock/{stockName}/chart/date/{date}:
    get:
      summary: Get stock chart.
      description: Retrieve stock chart.
      operationId: getStockChart
      parameters:
        - name: stockName
          in: path
          description: Stock name.
          required: true
          schema:
            type: string
            minLength: 1
            example: GOOG
        - name: date
          in: path
          description: Date.
          required: true
          schema:
            $ref: "#/components/schemas/DateISO8601"
      responses:
        200:
          description: Stock chart data.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/ChartEntry"
components:
  schemas:
    ChartEntry:
      required:
        - date
        - minute
        - close
      type: object
      properties:
        date:
          $ref: "#/components/schemas/DateISO8601"
        minute:
          type: string
          format: time
          maxLength: 5
          minLength: 5
          example: "09:07"
        close:
          type: number
          format: double
          minimum: 0.0
      description: Chart entry.
    DateISO8601:
      type: string
      format: date-ISO8601
      maxLength: 8
      minLength: 8
      example: "20190220"