apiVersion: v1
kind: Service
metadata:
  name: zipkin
spec:
  type: LoadBalancer
  ports:
    - port: 9411
      targetPort: 9411
      protocol: TCP
  selector:
    app: zipkin

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: zipkin
  labels:
    app: zipkin
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: zipkin
    spec:
      containers:
        - image: openzipkin/zipkin:2.12.0
          name: zipkin
          ports:
            - containerPort: 9411