apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: stats-monitor
  labels:
    app: stats
    component: monitoring
    release: microprofile-article
spec:
  selector:
    matchLabels:
      providesMetrics: "true"
  endpoints:
    - port: https
      scheme: https
      tlsConfig:
        insecureSkipVerify: true
      interval: "10s"

---

apiVersion: v1
kind: Service
metadata:
  name: stats
  labels:
    app: stats
    component: rest-application
    providesMetrics: "true"
spec:
  type: LoadBalancer
  ports:
    - name: https
      port: 443
      targetPort: 9443
      protocol: TCP
  selector:
    app: stats
    component: rest-application

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: stats
  labels:
    app: stats
    component: rest-application
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 50%
  selector:
    matchLabels:
      app: stats
      component: rest-application
  template:
    metadata:
      labels:
        app: stats
        component: rest-application
        providesMetrics: "true"
    spec:
      containers:
        - name: stats
          image: containerimageforstats
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: false
            readOnlyRootFilesystem: false
            allowPrivilegeEscalation: false
          ports:
            - containerPort: 9443
          env:
            - name: "KEY_STORE_LOCATION"
              value: "/app/keystore.pkcs12"
            - name: "KEY_STORE_TYPE"
              value: "PKCS12"
            - name: "KEY_STORE_PASSWORD"
              valueFrom:
                secretKeyRef:
                  name: stats-keystore
                  key: KEY_STORE_PASSWORD
            - name: "TRUST_STORE_LOCATION"
              value: "/app/truststore.pkcs12"
            - name: "TRUST_STORE_TYPE"
              value: "PKCS12"
            - name: "TRUST_STORE_PASSWORD"
              valueFrom:
                secretKeyRef:
                  name: truststore
                  key: TRUST_STORE_PASSWORD
            - name: "JWT_ISSUER"
              value: "https://user/token"
            - name: "JWT_PUBLIC_KEY_NAME"
              value: "user-public-key"
            - name: "DB_HOST"
              value: "stats-db"
            - name: "DB_PORT"
              value: "5432"
            - name: "DB_NAME"
              valueFrom:
                secretKeyRef:
                  name: stats-db
                  key: DB_NAME
            - name: "DB_USER_NAME"
              valueFrom:
                secretKeyRef:
                  name: stats-db
                  key: DB_USER
            - name: "DB_USER_PASSWORD"
              valueFrom:
                secretKeyRef:
                  name: stats-db
                  key: DB_PASSWORD
            - name: "DE_CONSOL_LABS_MICROPROFILEARTICLE_STATS_INTEGRATION_PROPHECY_PROPHECYAPI_GETPROPHECIESCREATEDBYUSER_RETRY_MAXRETRIES"
              value: "5"
            - name: "DE_CONSOL_LABS_MICROPROFILEARTICLE_STATS_INTEGRATION_PROPHECY_PROPHECYAPI_GETPROPHECIESCREATEDBYUSER_RETRY_DELAY"
              value: "500"
            - name: "DE_CONSOL_LABS_MICROPROFILEARTICLE_STATS_INTEGRATION_PROPHECY_PROPHECYAPI_GETPROPHECIESCREATEDBYUSER_RETRY_JITTER"
              value: "250"
          volumeMounts:
            - name: stats-keystore
              mountPath: "/app/keystore.pkcs12"
              subPath: stats-keystore.pkcs12
              readOnly: true
            - name: truststore
              mountPath: "/app/truststore.pkcs12"
              subPath: truststore.pkcs12
              readOnly: true
          livenessProbe:
            httpGet:
              scheme: HTTPS
              path: /health
              port: 9443
            timeoutSeconds: 3
            initialDelaySeconds: 15
            periodSeconds: 10
      volumes:
        - name: stats-keystore
          secret:
            secretName: stats-keystore
        - name: truststore
          secret:
            secretName: truststore

---

apiVersion: v1
kind: Service
metadata:
  name: stats-db
  labels:
    app: stats
    component: persistence
    providesMetrics: "false"
spec:
  ports:
    - port: 5432
      protocol: TCP
  selector:
    app: stats
    component: persistence

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: stats-db
  labels:
    app: stats
    component: persistence
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: stats
      component: persistence
  template:
    metadata:
      labels:
        app: stats
        component: persistence
        providesMetrics: "false"
    spec:
      containers:
        - image: postgres:11.1-alpine
          name: postgresql
          env:
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: stats-db
                  key: DB_NAME
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: stats-db
                  key: DB_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: stats-db
                  key: DB_PASSWORD
          ports:
            - containerPort: 5432

---

apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: check-stats-job
  labels:
    app: stats
    component: job
spec:
  schedule: "*/1 * * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: stats
            component: job
            providesMetrics: "false"
        spec:
          containers:
            - name: check-stats-job
              image: buildpack-deps:curl
              env:
               - name: "AUTHORIZATION_HEADER"
                 valueFrom:
                   secretKeyRef:
                     name: job-token
                     key: AUTHORIZATION_HEADER
              args:
                - /bin/sh
                - -ec
                - curl --request POST --insecure --verbose --header "${AUTHORIZATION_HEADER}" https://stats/stats/check
          restartPolicy: Never